version: '3'

services:
  ssr-service:
    container_name: ssr-service
    build:
      context: ./ssr/
      dockerfile: Dockerfile
    image: node:12
    restart: unless-stopped
    volumes:
      - './ssr:/usr/src/app'
      - './ssr/package.json:/usr/src/app/package.json'
      - './ssr/processes.json:/usr/src/app/processes.json'
      - './ssr/tsconfig.json:/usr/src/app/tsconfig.json'
      - '/usr/src/app/node_modules'
      - '/usr/src/app/dist'
      - '/etc/nginx/conf.d'
      
    networks:
      - app-network
 
  web-service:
    container_name: web-service
    build:
      context: ./web/
      dockerfile: Dockerfile
    image: nginx:1.15
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/src/app
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
      - /var/www/app
      - /etc/nginx/conf.d
    depends_on:
      - ssr-service
    networks:
      - app-network

#   certbot:
#     image: certbot/certbot
#     container_name: certbot
#     volumes:
#       - certbot-etc:/etc/letsencrypt
#       - certbot-var:/var/lib/letsencrypt
#       - web-root:/var/www/app
#     depends_on:
#       - web-service
#     command: certonly --webroot --webroot-path=/var/www/app --email prasad@example.com --agree-tos --no-eff-email --staging -d appengine.in  -d www.appengine.in -d stark-corp.appengine.in -d www.stark-corp.appengine.in -d wayne-corp.appengine.in -d www.wayne-corp.appengine.in

# volumes:
#   certbot-etc:
#   certbot-var:
#   web-root:
#     driver: local
#     driver_opts:
#       type: none
#       device: /home/prasad/pwa-ssr/views/
#       o: bind

networks:
  app-network:
    driver: bridge
   